---
GenerationParams:
  MapScale: 1.0          # how much the sectors are spread out  
  # float [0..1] solar systems are more like a cookie than a ball. the lower the value, the flatter the system
  SolarSystemSqueezeMinMax: [0.005, 0.1]
  # float [0..1] probability a warp connection will be one-way
  OneWayWarpProb: 0
  UniqueStarterPlanet: false
  
  #==== 1st Step of SolarSystem Generation: setting amount and playfield types  for System Content  ===

  PlanetCountProbs:
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Gas Giants
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Gas Planets
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Outer Gas Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stars
     - '0 : 0.9,   1 : 0.08,  2 : 0.02,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'               # 1 - Companion Stars

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Rocky Planets
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Hot
     - '0 : 0.6,   1 : 0.3,  2 : 0.1,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Desert
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 3 - Dead
     - '0 : 0.3,   1 : 0.3,  2 : 0.3,  3 : 0.1,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 4 - Temperate
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 5 - Ocean
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 6 - Alien
     - '0 : 0.5,   1 : 0.3,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 7 - Snow
     - '0 : 0.5,   1 : 0.3,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 8 - Barren
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 9 - Exotic

# ======================================================================================================================================================== Sector POIs

# -------------------------------------------------------------------------------------------------------------------------------------------------------- UCH and Admin POIs
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - UCH Research Vessel

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Asteroid Fields
     - '0 : 0.4,   1 : 0.4,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Asteroid Fields

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stations
     - '0 : 0.5,   1 : 0.5,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Anomalies

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Events
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Random Events



  PlanetLists:           # Lable name depicts, in a descriptive way, the class or global or visual approach of the playfields summarized under this lable; playfields are added in the *Types sections
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------- Gas Giants
    - 'Jupiter:1'                                                                   # 1 Gas
    - 'JupiterOuter:0.45, SaturnOuter:0.35, NeptuneOuter:0.2'                                                     # 2 Gas Outer
# -------------------------------------------------------------------------------------------------------------- Stars
    - 'SunB:0.00, SunA:0.00, SunG:1.00, SunF:0.00, SunM:0.00, SunD:0.00, SunN2:0.00, SunA4V:0.00'                 # 1 Companion Stars
# -------------------------------------------------------------------------------------------------------------- Rocky Planets
    - 'Lava:1.0, Lava2:0.0, Midnight:0.0'                                                                         # 1 Hot
    - 'Desert:0.4, Arid:0.4, DesertOasis:0.2, DesertBlack:0.0'                                                    # 2 Desert
    - 'Dead:1'                                                                                                    # 3 Dead
    - 'Temperate:0.5, Tropical:0.0, Swamp:0.3, Irradiated:0.2, Jungle:0.0'                                        # 4 Temperate
    - 'Ocean:1'                                                                                                   # 5 Ocean
    - 'Alien:1'                                                                                                   # 6 Alien
    - 'Snow:1.0, Ice:0.0'                                                                                         # 7 Snow
    - 'Barren:0.8, BarrenHot:0.2'                                                                                 # 8 Barren
    - 'Plasma:1, AlienLegacy:0.0, ProgenitorCore:0.0, IceGiant: 0.0'                                              # 9 Exotic
# ======================================================================================================================================================== Sector POIs
# -------------------------------------------------------------------------------------------------------------- UCH and Admin
    - 'UCHResearchShip:1.0'                                                                                         # 1 UCH Research Vessel
# -------------------------------------------------------------------------------------------------------------- Asteroid Fields
    - 'AsteroidField:0.4, AsteroidFieldPirate:0.2, AsteroidFieldPolaris:0.2, AsteroidFieldZirax:0.2'              # 1 Asteroid Fields
# -------------------------------------------------------------------------------------------------------------- Stations
    - 'TradeStationPolaris:1.0'                                                                                  # 1 Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------- Anomalies
# -------------------------------------------------------------------------------------------------------------- Events
    - 'PentaxidMining:0.5, SyndicateCasino:0.5, XenuanCarrier:0.0'                                               # 1 Random Events



# ======================================================================================================================================================== POIs
  POICountProbs: '0 : 0.60,  1 : 0.25,  2 : 0.15,  3 : 0.00,  4 : 0.00,  5 : 0.00,  6 : 0.00,  7 : 0.00,  8: 0.00'
# -------------------------------------------------------------------------------------------------------------------------------------------------------- POI counts
  POIs: 'SpaceEmpty: 0.00, POICombatT1: 0.30, POIExploreT1: 0.40, POIMiningT1: 0.30'
# --------------------------------------------------------------------------------------------------------------------------------------------------------
  PlanetTypes:

# -------------------------------------------------------------------------- Jupiter
      # - Name: SunG
        # Color: [1,0.95,0.63]
        # Icon: Sun
        # Placement:
            # - InnerSystem
        # MoonProb: '0:1'
        # MoonType: [EdenMoonBarren]
        # ForceSizeClass: [13,15]
        # HasOrbit: false
        # Playfields:
            # - SunRandom

      # - Name: SunG
        # Color: [1,0.95,0.63]
        # Icon: Sun
        # Placement:
            # - InnerSystem
        # MoonProb: '0:1'
        # MoonType: [EdenMoonBarren]
        # ForceSizeClass: [9,10]
        # # ForcePlanetType: [N, B, A]
        # ForcePlanetType: [Test2]
        # HasOrbit: false
        # Playfields:
            # - SunRandom

      - Name: RedDwarf
        Color: [0.8,0.3,0.1]
        Icon: Sun
        Placement:
            - InnerSystem
        MoonProb: '4:0.45, 5:0.35, 6:0.2'
        MoonType: [EdenMoonBarren, EdenMoonBarren, MoonTemperate, MoonLava, EdenMoonCrystal, MoonNascent]   
        ForceSizeClass: [9,11]
        # ForcePlanetType: [EdenSunRedDwarf]
        HasOrbit: false
        Playfields:
            - EdenSunRedDwarf


      - Name: Jupiter 
        Color: [0.22,0.54,0.69,  0.50,0.33,0.25,  0.68,0.56,0.26,  0.45,0.20,0.09,  0.38,0.27,0.40]
        # Distance: [100, 300]
        # Icon: GasGiant
        Icon: Sun
        Placement:                  # Defines where the playfield appears in the Solar system, related to the Galaxy.ecf Sun parameters: HabitableTemperate, HabitableHot, HabitableCold, InnerSystem, OuterSystem
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        MoonProb: '8:0.45, 9:0.35, 10:0.2'    # NEW definition of Moon Prob PLUS Count; Gauss. >> can be used for all other definitions in that file!!
        MoonType: [EdenMoonBarrenGasOuter, EdenMoonBarren, MoonIceOuter, EdenMoonMethane, EdenMoonVolcanic, MoonLava]
        MoonOrbitType: [DefaultOrbit]
        # Climate: Gas               # REQUIRED? > not required anymore
        # PlayfieldLevel: [1,10]     # REQUIRED? > sets default value if not set
        ForceSizeClass: [10,12]       # this is important for a gasgiant! if this is specified, the moons will not be put in the same sector as the gas giant (as the gas giant fills the whole sector)
        # ForcePlanetType: [JupiterBlue, JupiterBrown, JupiterYellow, JupiterBrown2, JupiterPurple]
        ForcePlanetType: [Test2]
        HasOrbit: false              # also a gasgiant may never have an orbit!
        Playfields:
            - SunRandom
            # - GasGiant
            
            
            
            
      - Name: Saturn 
        Color: [0.22,0.54,0.69,  0.33,0.20,0.14,  0.68,0.56,0.26,  0.25,0.53,0.05,  0.38,0.27,0.40]
        Icon: GasGiantRing
        # Distance: [100, 300]
        Placement:                  # Defines where the playfield appears in the Solar system, related to the Galaxy.ecf Sun parameters: HabitableTemperate, HabitableHot, HabitableCold, InnerSystem, OuterSystem
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        MoonProb: '1:0.5, 2:0.3, 3:0.2'    # NEW definition of Moon Prob PLUS Count; Gauss. >> can be used for all other definitions in that file!!
        MoonType: [DefaultMoon, MoonIce]   
        MoonOrbitType: [OrbitSectorStarter]
        # Climate: Gas               # REQUIRED? > not required anymore
        # PlayfieldLevel: [1,10]     # REQUIRED? > sets default value if not set
        ForceSizeClass: [8,11]       # this is important for a gasgiant! if this is specified, the moons will not be put in the same sector as the gas giant (as the gas giant fills the whole sector)
        ForcePlanetType: [SaturnBlue, SaturnBrown, SaturnYellow, SaturnGreen, SaturnPurple]
        HasOrbit: false              # also a gasgiant may never have an orbit!
        Playfields:
            - GasGiant

# =================================================================================================================================================================================
#                                                                                                                Stations
# =================================================================================================================================================================================
  # StationTypes:
      # - Name: SpaceTradingStation
        # Color: [0.7, 0.5, 0.0]
        # Icon: Station
        # Distance: [200, 300]
        # Placement: 
          # - InnerSystem
        # HasOrbit: false
        # HasTerrain: false
        # PlayfieldLevel: [2,10]
        # Playfields:
            # - SpaceTradingStation
            
  OrbitTypes:
# -------------------------------------------------------------------------- DefaultOrbit
      - Name: DefaultOrbit     # definition of default name 'DefaultOrbit' is mandatory
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            # - EdenSpaceG_Orbit
            - TestOrbit

  WarpTargetOrbitTypes:
# -------------------------------------------------------------------------- Sun Playfield
      - Name: WarpTarget
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [1,4]
        Playfields:
            - EdenSpaceWarpTargetG
