---
GenerationParams:
  MapScale: 1.0          # how much the sectors are spread out  
  # float [0..1] solar systems are more like a cookie than a ball. the lower the value, the flatter the system
  SolarSystemSqueezeMinMax: [0.005, 0.05]
  # float [0..1] probability a warp connection will be one-way
  OneWayWarpProb: 0
  UniqueStarterPlanet: false
  
  #==== 1st Step of SolarSystem Generation: setting amount and playfield types  for System Content  ===

  PlanetCountProbs:
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Gas Giants
     - '0 : 0.9,   1 : 0.1,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Gas Planets
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Outer Gas Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stars
     - '0 : 0.85,   1 : 0.10,  2 : 0.05,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'               # 1 - Companion Stars

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Rocky Planets
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Hot
     - '0 : 0.4,   1 : 0.4,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Desert
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 3 - Dead
     - '0 : 0.5,   1 : 0.4,  2 : 0.1,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 4 - Temperate
     - '0 : 0.9,   1 : 0.1,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 5 - Ocean
     - '0 : 0.6,   1 : 0.4,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 6 - Alien
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 7 - Snow
     - '0 : 0.3,   1 : 0.5,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 8 - Barren
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 9 - Exotic

# ======================================================================================================================================================== Sector POIs
# ------------------------------------------------------------------------------------------------- Main
     - '0 : 0.3,   1 : 0.7,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                              # 1 - Trading Station
# ------------------------------------------------------------------------------------------------- Zirax
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                              # 1 - Asteroid Fields
# ------------------------------------------------------------------------------------------------- Polaris
     - '0 : 0.4,   1 : 0.4,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                              # 1 - Asteroid Fields
# ------------------------------------------------------------------------------------------------- Trader

# ------------------------------------------------------------------------------------------------- Colonists

# ------------------------------------------------------------------------------------------------- Pirates
     - '0 : 0.4,   1 : 0.4,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                              # 1 - Asteroid Fields
# ------------------------------------------------------------------------------------------------- Warlord

# ------------------------------------------------------------------------------------------------- Alien

# ------------------------------------------------------------------------------------------------- UCH and Admin POIs
     - '0 : 0.9,   1 : 0.1,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - UCH Research Vessel

# ------------------------------------------------------------------------------------------------- Asteroid Fields
     - '0 : 0.0,   1 : 0.5,  2 : 0.5,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Asteroid Fields

# ------------------------------------------------------------------------------------------------- Stations
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Polaris Trade Station

# ------------------------------------------------------------------------------------------------- Anomalies

# ------------------------------------------------------------------------------------------------- Events
     - '0 : 0.5,   1 : 0.2,  2 : 0.1,  3 : 0.1,  4 : 0.1,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Random Events



  PlanetLists:           # Lable name depicts, in a descriptive way, the class or global or visual approach of the playfields summarized under this lable; playfields are added in the *Types sections
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------- Gas Giants
    - 'Jupiter:0.45, Saturn: 0.35, Neptune:0.2'                                                                   # 1 Gas
    - 'JupiterOuter:0.45, SaturnOuter:0.35, NeptuneOuter:0.2'                                                     # 2 Gas Outer
# -------------------------------------------------------------------------------------------------------------- Stars
    - 'SunB:0.00, SunA:0.10, SunG:0.30, SunF:0.10, SunM:0.40, SunD:0.00, SunN2:0.00, SunA4V:0.10'                 # 1 Companion Stars
# -------------------------------------------------------------------------------------------------------------- Rocky Planets
    - 'Lava:1.0, Lava2:0.0, Midnight:0.0'                                                                         # 1 Hot
    - 'Desert:0.5, Arid:0.3, DesertOasis:0.2, DesertBlack:0.0'                                                    # 2 Desert
    - 'Dead:1'                                                                                                    # 3 Dead
    - 'Temperate:0.5, Tropical:0.0, Swamp:0.3, Irradiated:0.2, Jungle:0.0'                                        # 4 Temperate
    - 'Ocean:1'                                                                                                   # 5 Ocean
    - 'Alien:1'                                                                                                   # 6 Alien
    - 'Snow:0.5, IceBlack:0.5'                                                                                         # 7 Snow
    - 'Barren:0.8, BarrenHot:0.2'                                                                                 # 8 Barren
    - 'Plasma:1, AlienLegacy:0.0, ProgenitorCore:0.0, IceGiant: 0.0'                                                                                 # 9 Exotic
# ======================================================================================================================================================== Sector POIs
# ------------------------------------------------------------------------------------------------- Main
    - 'TradingStationMain:1'              # 1 Trading Station
# ------------------------------------------------------------------------------------------------- Zirax
    - 'AsteroidFieldZirax:1'              # 1 Asteroid Fields
# ------------------------------------------------------------------------------------------------- Polaris
    - 'AsteroidFieldPolaris:1'              # 1 Asteroid Fields
# ------------------------------------------------------------------------------------------------- Trader

# ------------------------------------------------------------------------------------------------- Colonists

# ------------------------------------------------------------------------------------------------- Pirates
    - 'AsteroidFieldPirate:1'              # 1 Asteroid Fields
# ------------------------------------------------------------------------------------------------- Warlord

# ------------------------------------------------------------------------------------------------- Alien

# ------------------------------------------------------------------------------------------------- UCH and Admin
# -------------------------------------------------------------------------------------------------------------- UCH and Admin
    - 'UCHResearchShip:1.0'                                                                                       # 1 UCH Research Vessel
# -------------------------------------------------------------------------------------------------------------- Asteroid Fields
    - 'AsteroidFieldG:0.7, AsteroidFieldGPoor:0.3'              # 1 Asteroid Fields
# -------------------------------------------------------------------------------------------------------------- Stations
    - 'TradeStationPolaris:1.0'                                                                                   # 1 Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------- Anomalies
# -------------------------------------------------------------------------------------------------------------- Events
    - 'PentaxidMining:0.5, SyndicateCasino:0.5, XenuanCarrier:0.0'                                                # 1 Random Events



# ======================================================================================================================================================== POIs
  POICountProbs: '0 : 0.30,  1 : 0.20,  2 : 0.20,  3 : 0.15,  4 : 0.05,  5 : 0.05,  6 : 0.05,  7 : 0.00,  8: 0.00'
# -------------------------------------------------------------------------------------------------------------------------------------------------------- POI counts
  POIs: 'SpaceEmpty: 0.00, POICombatT1: 0.40, POIExploreT1: 0.30, POIMiningT1: 0.30'
# --------------------------------------------------------------------------------------------------------------------------------------------------------

# =================================================================================================================================================================================
#                                                                                                                Orbits
# =================================================================================================================================================================================
  OrbitTypes:
# -------------------------------------------------------------------------- DefaultOrbit
      - Name: DefaultOrbit     # definition of default name 'DefaultOrbit' is mandatory
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - EdenSpaceG_Orbit

# =================================================================================================================================================================================
#                                                                                                                Stations
# =================================================================================================================================================================================
  StationTypes:
      # - Name: SpaceTradingStation
        # Color: [1, 1, 1]
        # Icon: Station
        # Distance: [200, 300]
        # Placement:
            # - InnerSystem
            # - HabitableHot
            # - HabitableTemperate
            # - HabitableCold
        # HasOrbit: false
        # HasTerrain: false
        # PlayfieldLevel: [2,10]
        # Playfields:
            # # - SpaceTradingStation
            # - EdenSpace_TradingStation

  WarpTargetOrbitTypes:
# -------------------------------------------------------------------------- Sun Playfield
      - Name: WarpTarget
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [1,4]
        Playfields:
            - EdenSpaceWarpTargetA
